### ISSUE TITLE
it is not working in xapp

### ISSUE THREAD

**Issue by tk-t0n0y** [lucasmartinelle/Bounty-Dashboard#3]
hi there ,

thanks for bounty_dashboard  . but it is not working in xapp localhost ... plz fix this ...

and it is not my xapp problem because other web working without any error but bounty-dashboard is not 

:🥺🥺🥺🥺🥺🥺🙂🙂🙂🙂🙂🙂

**Comment by JoshuaMart** [comment]
Hello,
The last update allows an installation with Docker, the project is initially not designed to run on Windows.

It is however possible to modify the configuration files in order to adapt the path to your needs (do not use `/var/www` but something like `C:\xammp`)

However, the project is being redesigned to use Symfony but we prefer to deploy it via Docker (which makes things easier) rather than providing support specific to each user's configuration.

Regards
